name: CI
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check Lua formatting
        run: nix develop --command "stylua" "--check" "."

      - name: Run Lua tests
        run: nix develop --command "run-tests"
  build:
    name: Nix build on ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - run: nix flake check
      - run: nix develop --command "stylua" "--version"
      - run: nix build .
